### ISSUE TITLE
Make dependencies "private" by default

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#101]
We may want to make dependencies "private" by default, meaning they would not forward public includes and flags.
**The question is how public dependencies would then be declared.**

This issue depends on issue #100.

A few facts to note:
- currently, the behaviour is like all dependencies are public
- interface dependencies do not make sense
- interface includes do not make sense

**Benefits:**
- the build commands of targets with long dependency chains would be cleaned up
- less potential for accidentally choosing the wrong header for an include

----------------------------------------

**The complete set of inheritance rules would be:**
- private flags and includes are
    - changed to public for headeronly targets
    - applied to target itself, unless headeronly
    - never applied to dependent targets
    - never forwarded
- public flags and directories are
    - applied to the target itself, unless headeronly
    - applied to all dependent targets, except headeronly
    - not forwarded from private dependencies
    - forwarded from public dependencies
- interface flags are
    - never applied to the target itself
    - applied only to dependent shared libraries and executables
    - forwarded only by dependent static libraries

----------------------------------------

The following cases should illustrate a little:
1. `shared libA -private-> shared libB` (libB is used only internally and its headers are not exposed in the interface of libA).
    Public includes and flags are applied to libA, but not forwarded.
    Interface flags are applied to libA, but not forwarded.
2. `shared libA -public-> shared libB` (the interface of libA includes headers of libB).
    Public includes and flags are applied to libA and forwarded.
    Interface flags are applied to libA, but not forwarded.
3. `static libA -private-> shared libB` (libB is used only internally and its headers are not exposed in the interface of libA).
    Public includes and flags are applied to libA, but not forwarded.
    Interface flags are forwarded by libA, but not applied.
4. `static libA -public-> shared libB` (the interface of libA includes headers of libB).
    Public includes and flags are applied to libA and forwarded.
    Interface flags are forwarded by libA, but not applied.

**Comment by NOhs** [comment]
I am working on a similar issue currently where I change the default behaviour of the public header search to not perform a search if no explicit public include locations are given.

**Comment by GPMueller** [comment]
Note that the documentation, in particular `inheritance.rst` needs to be reviewed for statements such as

> interface flags are not forwarded beyond a shared library, while public flags are
forwarded up until an executable

**Comment by GPMueller** [comment]
A first draft of the updated documentation from PR #127 can be viewed here: [c358385c/docs/user_guide/inheritance.rst](https://github.com/Trick-17/clang-build/blob/c358385cbde3c0404add5586fa343ab32403fd9b/docs/user_guide/inheritance.rst)
