### ISSUE TITLE
Subprocess functions

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#11]
Subprocess functions should not be called with shell=True (see e.g.: https://stackoverflow.com/questions/3172470/actual-meaning-of-shell-true-in-subprocess). This way you do not have to take care to tailor your call string to different platforms, among other benefits.

**Comment by GPMueller** [comment]
Removed `shell=True` with 951892d4c4acdee6657397f52fedb557afe00fda.

I believe the call strings do not need to be different on different platforms, as `clang` seems to have the same syntax for being passed flags everywhere - or am I missing something?

**Comment by GPMueller** [comment]
For some reason, the builds won't run on Linux or OSX when `shell=True` is not used: https://travis-ci.org/Trick-17/clang-build/builds/358049584

**Comment by GPMueller** [comment]
Fixed the subprocess calls with 2f295536d0449f2689531b58add8ea65e30fc294.
