### ISSUE TITLE
Path separators

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#12]
Path separators shouldn't be hardcoded into your scripts. Although it works most of the times, there are modules like PathLib2 that take away all the hassle with python path separators. E.g. if you are on windows, you have a folder that starts with U and you manipulate those strings (like adding a filename to the end of the path), python will not like that newly created string (see here: https://docs.python.org/3/howto/unicode.html for the example I gave).

**Comment by GPMueller** [comment]
It seems that everything is now coded properly on PR #23, right?

**Comment by GPMueller** [comment]
Merged with a7bbc88738d7863cfe6f0994f80914a99914d417.
