### ISSUE TITLE
Missing Release flags

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#18]
Looking at:
https://github.com/Trick-17/clang-build/blob/e4dc87a47151ad6d43c1d205adf9ff7d23466092/clang_build/clang_build.py#L291-L312

It seems that while the releaseFlags of the dependencies are included, for the target itself only the default release flags are included.

**Comment by NOhs** [comment]
This code anyways has the issue that externally one has to check which flags to obtain from an object that very well knows which flags it should return...

**Comment by GPMueller** [comment]
It's correct that build types are not yet implemented correctly. By the second commend do you mean that the Target should provide a function, e.g. `getFlags`, which encompasses these checks?

In this context: should the `buildType` really be a property of `Target`? It seems more sensible to have it as a global variable, as different build types should never be mixed anyways (at least between dependent targets)!

**Comment by GPMueller** [comment]
Fixed the missing Release (and Debug) flags with bf61b42dec80e6ff176f6a74ff9a2de8f27f17f4.
The flags are now generated successively, starting at the leaf nodes and are thereby propagated up the dependency graph.

I think this upwards propagation will not always be the right choice and we should re-visit this.
