### ISSUE TITLE
Inconsistency between with and without toml configuration file scenario

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#19]
If a toml file (even a very simple one), sources are expected to be in the src folder. However, without a toml file, clang-build will look directly in the target folder. To me this has several disadvantages:
- more heterogenious project structures (some with src folder, others just having the source files directly in the top directory
- restructuring of the project when adding a toml file later, or breaking the default (both are cumbersome)
- messy code

I also see the advantage that clang-build is more usable for quick tests as no special folder structure is required. However, creating a single 'src' folder is not really *effort* and so I am not sure how much this point is actually relevant.

**Comment by GPMueller** [comment]
For me the main argument is that trivial projects should really be trivial to build. Project structures will always be somewhat heterogeneous and people will choose a build system etc. to suit their taste. As long as we don't have features with the sole purpose of supporting legacy project structures or the different tastes of different people, I think it's fine.

**Comment by GPMueller** [comment]
Note that also the build directories currently differ for "anonymous" targets (i.e. without build config) and named targets. But I think that's probably unproblematic.
