### ISSUE TITLE
Mix up of paths in readme

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#20]
I think the list of include folders is mixed up in the readme. The $PATH normally isn't searched for included headers as far as I am aware for example. I would much rather state that all the paths that clang by default searches **plus** the `include` folder are paths which are searched through by default by clang-build.

see also here: https://stackoverflow.com/a/11946295/2305545

**Comment by GPMueller** [comment]
We should definitely state that clang's search paths are used (maybe with a link to the clang documentation).
I thought it might be sensible to add further search folders which are frequently used but not in there.
*For dependency management, the `clang-build` package directories should be searched.*

I think it's not implemented yet, but if a target name or root folder is given, it may make sense to also add `<targetname/include>` and `<targetroot>/include` to the search paths (if they exist!).
The default of this project should be that such standard directory structures do not need to be explicitly put into the .toml.

**Comment by NOhs** [comment]
At the moment in my branch I am pooling the include paths of all dependencies as well.

**Comment by NOhs** [comment]
Fixed with #23
