### ISSUE TITLE
Dependent headers are updated AFTER the check if new header dependencies exist

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#21]
Looking at the code we see that the function to generate the dependency files is called after checking the dependency file for updated headers. So the first time the build is run, obviously no dependency file exists which is ok, as it is clear that we need to compile the first time we run clang-build. However, the second time, the dependency file is checked to see if some of the headers changed. But the dependency file might be outdated and some new headers made it into the target. This is not captured. Or am I missing something here?

**Comment by GPMueller** [comment]
There are two cases (non-exclusive) when an object needs to be re-built:
1. the source file was changed
2. one of the files the source file depends on changed

An additional dependency, added by changing the corresponding source file, is trivial to detect (category 1).

When the header file or an indirect include was changed, this will be noticed via the modification dates of those files and the dependency file will be re-generated and the object re-built.
This should cover the case you described, right?

**Comment by NOhs** [comment]
what are they if not header files? Anyways, I think you are right, the case is covered.

**Comment by GPMueller** [comment]
One can also `#include` cpp source files (although that's bad practice). In principle any file the corresponding source file depends on is written into its depfile.
But it shouldn't make any difference here.
