### ISSUE TITLE
Add ability to call external scripts at certain places

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#22]
1. Before any target is parsed
2. Before the build, i.e. before any target is compiled
3. Before any target is linked
4. After the build has finished

Specifying any Python script to be executed would suffice, as any configuration steps etc. (e.g. to create a header with version information) could be done well in Python.

**Comment by NOhs** [comment]
This is indeed a good idea. I am also considering adding functions in the classes in my branch like:
- run_before
- run_after_compile
- run_after_linking

which are just empty functions. But then we could allow ppl to write custom targets that are derived from the default ones filling in those functions.

**Comment by GPMueller** [comment]
Added external scripting via `targetname.scripts` with fields `before_compile`, `before_link` and `after_build` in 79cc6bd8e17a328d9e6a0fbdada2ba88600423aa.

**Comment by GPMueller** [comment]
Added on master with 3d12899ccc4b50271d0dd38002c1a801fbb1c2f5, including a test.

**Comment by GPMueller** [comment]
Test passing since 47d3baa266ad8b1fa932c382d1b3894e9e769987 (OSX failed due to #30).
