### ISSUE TITLE
Remove all `sys.exit(1)` from within the code

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#27]
Pulling the plug just because something unexpected happend is not a calm response and makes error tracking/debugging tough. It also makes it impossible to include that code in anything else knowing that it could just exit. We should replace the occurrences of `sys.exit(...)` with proper exceptions which we should deal with in the `main` function.

**Comment by GPMueller** [comment]
Since d0a309012b652da928f8fca3e719dff1c230e14f, only two instances remain:

https://github.com/Trick-17/clang-build/blob/d0a309012b652da928f8fca3e719dff1c230e14f/clang_build/clang_build.py#L84-L101

**Comment by GPMueller** [comment]
This was finished by the merge of PR #53 (e0cd95e841908efbed620b008e1794a12417555a).
