### ISSUE TITLE
PyPi release on every branch will lead to issues with pbr and its naming scheme

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#30]
pbr has the naming scheme version + commits since version. This can conflict for multiple branches. I also do not see the necessity to push every commit to pypi. I would limit it to the master branch. Most people will anyways only care for tagged releases.

**Comment by GPMueller** [comment]
This issue, so far, is specific to PR #23, where I also suggested a different tagging scheme in a comment. A commit-datetime tag is very unlikely to create collisions and gives the packages a chronological order. Do you think that would be sufficient?

**Comment by NOhs** [comment]
I don't see a need for pushing so many non-working versions to PyPi, it seems kind of not in the spirit of the PyPi system if everybody just pushes every possible commit to it. I mean, it is not meant as a back-up system of your commit history :D. I mean development release are fine, but not every commit?

**Comment by GPMueller** [comment]
The non-working versions are of course not useful, but in general providing a develop version (and also also of feature branches) seems sensible to me.

**Comment by GPMueller** [comment]
Fixed on PR #59, merged with 1bf1cb7d34f9f3d907bebf9bca889599075d948b by disabling deployments on non-master branches.
