### ISSUE TITLE
Add `clang-build create` feature?

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#33]
This could simply create a basic project, to make it easier for people to create projects with a sane structure and basic config which can be easily built with clang-build.

The question is whether this makes sense since the simple kind of project, which could be created without any knowledge about the goals of the project, could be built without any project configuration file...

Maybe by adding more options, such as `create type=executable name=myexe` this would become more useful. But would it really help anyone?

**Comment by NOhs** [comment]
I am also not sure what the advantage would be. You basically mentioned already that simple projects anyways do not require any configuration, and for your example I guess most people would just in their editor create a file and put `[myexe]` in there which is faster than looking up what the clang-build command was again to initialize... I mean create such a tiny config.

So my vote would be on no advantage and therefore not worth spending time on.

**Comment by GPMueller** [comment]
The only advantage would be to have a quick way to set up a project with a sensible structure. But I guess it does not make much sense for C++ projects in general (of any size), as one would need to make assumptions, such as names...
