### ISSUE TITLE
More warnings

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#39]
I think the following flags should be added to the defaults:

```
-fsanitize=address
```

see https://clang.llvm.org/docs/AddressSanitizer.html

and also
```
-Wshadow
```

seem useful flags for writing clean code. The first one can help identify illegal access mistakes and the second one can help finding shadowing bugs like in e.g. nested loops where the loop variables are shadowed in one of the inner loops.

**Comment by GPMueller** [comment]
Should behave the same as in gcc, so according to https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html `-Wshadow` is not activated by `-Wall` or `-Wextra`.

We should maybe also add `-Wpedantic`. People who do not want to be ISO-conformant should probably manually set all their flags.

And what about `-fsanitize=leak` and `-fsanitize=undefined`, see https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html#Instrumentation-Options

**Comment by NOhs** [comment]
I agree to add all your suggestions.

**Comment by GPMueller** [comment]
Unfortunately
- `-fsanitize=leak` won't work, at least on windows: `clang++.EXE: error: unsupported option '-fsanitize=leak' for target 'x86_64-pc-windows-msvc'`
- it seems `-fsanitize=address` and `-fsanitize=undefined` should be also passed to the linker, but not for static libraries

**Comment by GPMueller** [comment]
As the documentation ([address](https://clang.llvm.org/docs/AddressSanitizer.html), [undefined behaviour](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)) states, there is no run-time performance impact of ubsan, but asan gives a ~2x slowdown.
Should we
- add sanitizers to the default debug flags (increase optimisation to `O1` and add `-fno-optimize-sibling-calls -fno-omit-frame-pointer`)?
- create a new `sanitize` build type?

**Comment by GPMueller** [comment]
I decided to add sanitizers directly to the debug build on PR #99. This can easily be changed later, if we feel that there should be a separate build type.
