### ISSUE TITLE
External keyword might be unnecessary

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#42]
It seems to me that we can infer from the input in the toml if the target is external or not. So maybe it is not needed. This would simplify the toml script and be in line with the idea to make everything as simple/smart as possible.

**Comment by GPMueller** [comment]
Agreed. If a url is specified, the target is automatically external and if it comes from a directory, there is no need to copy the sources into the build directory.

**Comment by GPMueller** [comment]
Implemented on PR #44, which was merged with d0a309012b652da928f8fca3e719dff1c230e14f.
