### ISSUE TITLE
Stop build at first failure

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#5]
Currently the program may continue to run for quite a while, trying to build parent targets of the failed target.

**Comment by NOhs** [comment]
In my current branch I topologically sort the targets in the dependency graph and go through it target by target. So we could abort as soon as a target fails.

**Comment by GPMueller** [comment]
It could suffice to simply not call the parent's `compile` function (and to not set `compiled = True`, when the failure of a build command is detected, as this would automatically keep any parent from being compiled.

**Comment by GPMueller** [comment]
With PR #23, merged with a7bbc88738d7863cfe6f0994f80914a99914d417, it has been implemented that sources are built as far as possible and at link-time, the build is stopped when a target is encountered, containing sources that were not able to build.
