### ISSUE TITLE
Allow Python scripts as variable assignments?

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#54]
This could be done by allowing e.g.
```Python
output_name  = "script: myname.py"
[mylib.sources]
include_directories = "script: mypaths.py"
```
i.e. if the variable is a string and starts with "script:" and ends with ".py", the contents after the "script:" is interpreted as a path (whitespace should be trimmed).
If the file is found, it is executed and the return is assigned to the corresponding variable.
Then, checks should be run to make sure that the variable has the right form (e.g. a string or a list).

This more general setting of variables would for example allow build processes with platform-dependencies.

**Comment by NOhs** [comment]
We do not necessarily need the ending. The following would do:

```python
variables = {}
with open(script) as f:
    exec(f, variables)

print(variables)
```

However, like this we would need to define what the variable needs to be called.

**Comment by GPMueller** [comment]
Maybe for system-dependent things it's enough to allow an external target of the type
```toml
[python]
target_type = "pre-installed"
url = "..." # where to find the "plugin" script
```
where the plugin script would define the `pre-installed` target containing
- `include_directories`
- `compile_flags`
- `link_flags`

**Comment by GPMueller** [comment]
I no longer believe this is a reasonable approach and will close this in favour of a proper scripting API, as described in issue #87.
