### ISSUE TITLE
Logging setup mixed into main function

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#60]
Logging setup is part of the ``Environment`` constructor. Logging formatting setup, however, should not be part of the clang build main function. Changing this will fix the tests logging everything multiple times.

**Comment by GPMueller** [comment]
At which point should the logger be setup instead?
Also, the now unneeded '-p' flags can be removed from the test.py to clean up the output.

**Comment by GPMueller** [comment]
Fixed with 8a9f8c229d7cd484d77da3b1f2dca74211d253cf on `feature-sources-patterns` (PR #63).

**Comment by GPMueller** [comment]
Merged with 013871d3d3b8d789c61b9f5d0f574ba0f295cec8.
