### ISSUE TITLE
Comment and code contradict each other

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#77]
Looking at the following code:

https://github.com/Trick-17/clang-build/blob/c5d5c1bba495566e7a2936e84593fed04f0b136f/clang_build/target.py#L76-L80

We see that while the comment says that header only targets' include directories are always public, this is not realized in the actual code, hence requiring this unnecessary check to then also include the "non-public" include directories of header only targets.

**Comment by GPMueller** [comment]
You mean the headeronly target should not have any flags in the non-public member variable? The comment refers to the behaviour the user should experience.

**Comment by NOhs** [comment]
The header only target should have all `include_directories` in the `self.include_directories_public` so it behaves as the user experiences it and does not require some extra treatment. It is not a bug, more like a design issue imho.

**Comment by GPMueller** [comment]
Agreed, this would be better. There might be some places in the __init__ that need changing, I think some defaults are placed in those variables for all target kinds.

**Comment by NOhs** [comment]
I am currently trying to get an overview of the init function, I think it can be simplified a bit and at the same time the above mentioned can be implemented.

**Comment by NOhs** [comment]
Should be "fixed" with https://github.com/Trick-17/clang-build/pull/76
