### ISSUE TITLE
Potential bug in flags order

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#81]
https://github.com/Trick-17/clang-build/blob/c5d5c1bba495566e7a2936e84593fed04f0b136f/clang_build/target.py#L122-L160

As you can see in the code above, the target's general flags are **before** the dependency flags, whereas the public flags are **after** the dependency flags. I mean these are all ugly scenarios where this would matter, but I think the current solution is very un-intuitive. We should decide which one comes first, and then do it for all (private/public/interface).

**Comment by GPMueller** [comment]
I agree. The interface and public flags of the target should simply be moved in front of the dependency flags and that would do it, right?

Or are you suggesting e.g. the public flags (target + dependency) come first, then the interface (again target + dependency) etc.?

**Comment by NOhs** [comment]
I think the dependency flags should be moved in front of the target flags. Not having the option to override dependency flags in the current target would be very annoying. E.g. the dependency says `std14` but you want `std17`.

**Comment by GPMueller** [comment]
I agree, as long as in such cases the last flag is indeed the one that is used and this doesn't instead result in an error. As far as I can tell this is the case.

*Note if the above does not hold:* for flags that definitely don't collide (e.g. include directories, `-I ...`) I believe it is nicer to read if the target's own flags come first.
