### ISSUE TITLE
Ability to only (re-)build a specific set of Targets?

### ISSUE THREAD

**Issue by GPMueller** [Trick-17/clang-build#9]
This may be sensible to have, e.g. for rebuilding only a single test executable.

**Comment by NOhs** [comment]
I agree, this is a must have that everybody wanting an easy to use system would expect.

**Comment by GPMueller** [comment]
After the implementation of #49, this has now been implemented with 7162cd7488808c1360ce7ff04f5e7f7e4cb9e6a9 on `feature-sources-patterns` (see PR #63).

- `-t`/`--targets` takes a string containing comma-separated target names. Only those and their dependencies will be built. if `-a` is passed this flag cannot be passed as well.
- `-f`/`--force-rebuild` forces those targets, which are checked for the need to be rebuilt to be built in any case. This works quite nicely together with `-t` to rebuild a specific target.

**Comment by GPMueller** [comment]
Merged with 013871d3d3b8d789c61b9f5d0f574ba0f295cec8.
