### ISSUE TITLE
project identifier vs name

### ISSUE THREAD

**Issue by NOhs** [Trick-17/clang-build#91]
Just a quick reminder, what do we have "project identifier" AND "name"?

**Comment by GPMueller** [comment]
If I understand the question correctly: to distinguish targets of the same name that come from different projects. Together they form the target identifier. For example one might have a "myproject.graph" which uses "boost.graph".

Note that the project identifier may be nested through subprojects, e.g. "myproject.mysubproject.boost.graph".
